### ISSUE TITLE
Doesn't run on Windows10

### ISSUE THREAD

**Issue by plcs2eco** [Atlantis-Software/node-turn#10]
When I do, server.start();, I got the below error.  It looks like node-turn found three IP addresses as listeningIps.   One of them is "::1".    It looks like node-turn is trying to bind 3478 port number onto the "::1" address and failed.  Please help me on this?

This happens right after the below line at 19 in network.js.
    const udpSocket = dgram.createSocket('udp4');

Error: bind EINVAL ::1:3478
address: "::1"
code: "EINVAL"
errno: "EINVAL"
message: "bind EINVAL ::1:3478"
port: 3478
stack: "Error: bind EINVAL ::1:3478
    at state.handle.lookup (dgram.js:301:18)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11"
syscall: "bind"
__proto__: Object {constructor: , name: "Error", message: "", …}

In the node-turn instance, listningIps: Array(3) ["10.243.22.33", "::1", "127,0,0,1"]

**Comment by plcs2eco** [comment]
I am using node-turn "0.0.4"

**Comment by plcs2eco** [comment]
And even though I still get the above error, when I check the port 3478, it is used by node.js.  When I stop the program, the same command in cmd shows no address is bind to 3487.  Does this mean, it's running and caused an error with one of the three addresses "listeningIps", "::1" address?

C:\Users\9033113>netstat -nao|find "3478"
  UDP         10.243.22.33:3478      *:*                                    13940
  UDP         127.0.0.1:3478         *:*                                    13940

**Comment by st-ah** [comment]
As far as i know this lib by default try to listen on ALL interfaces(ip address). It seems that win10 have some problem with binding to IPv6 addresses. I faced the same issue. To solve it try to provide some specified listening address:
```javascript
const turnServer = new Turn({
  authMech: 'long-term',
  credentials: {
    test: "test"
  },
  listeningIps: ['172.18.105.17']
});
```

**Comment by oxygen** [comment]
Shouldn’t node-turn attempt to listen correctly on its own?

**Comment by atiertant** [comment]
@oxygen node-turn actually try to listen on every interfaces ips even on ipV6 that is not supported.
ipV6 should be discard at start as long as ipV6 is not supported

**Comment by atiertant** [comment]
0.0.5 now should work on windows with ipv6
