### ISSUE TITLE
invalid STUN message length

### ISSUE THREAD

**Issue by jespertheend** [Atlantis-Software/node-turn#12]
My server crashed with this error at [message.js:88](https://github.com/Atlantis-Software/node-turn/blob/master/lib/message.js#L88). Is there any way to catch this and prevent the server from crashing?

**Comment by heinerwalter** [comment]
The same error occurrs on my server every once in a while. Have you already found a solution?

**Comment by jespertheend** [comment]
Hmm I haven't seen this error in a while now. I don't remember solving this, and I don't see any try catch statements in my code either. I think this might not actually be crashing the server? Maybe it just prints a warning in the console?

**Comment by atiertant** [comment]
should be fixed in 0.0.6
