### ISSUE TITLE
TURN server failing after a minute

### ISSUE THREAD

**Issue by TreeOfSelf** [Atlantis-Software/node-turn#13]
I managed to finally get my AT&T cellphone connection to connect to my wifi through simple peer using node-turn. Sadly, it seems after a minute or so the connection failed. This is what consistently shows in the log:

> `
> relaying data fromIPV4://97.121.170.121:60183 over channelNumber 16387 to IPV4://166.177.121.0:12273
> relaying data fromIPV4://97.121.170.121:60183 over channelNumber 16387 to IPV4://166.177.121.0:12273
> relaying data fromIPV4://97.121.170.121:60183 over channelNumber 16387 to IPV4://166.177.121.0:12273
> relaying data fromIPV4://97.121.170.121:60183 over channelNumber 16387 to IPV4://166.177.121.0:12273
> Receiving UDP: from IPV4://166.177.121.0:12273 to IPV4://shrek.best:3478 refresh request TransactionID: 2b7569575a2b355632304b57
>   lifetime: 0
>   username: user
>   realm: shrek.best
>   nonce: 16f6398d044aba5381cedde7309fdb4c
>   message-integrity: ee8f931a1dc5899d1e5c414e5ce2502e0cf93fb1
> Sending UDP: from IPV4://shrek.best:3478 to IPV4://166.177.121.0:12273 refresh success TransactionID: 2b7569575a2b355632304b57
>   lifetime: 0
>   software: node-turn
>   message-integrity: d12e0880dcd3dfe7ca37541f20cd02076b20f1e9
> relaying data fromIPV4://97.121.170.121:60183 over channelNumber 16387 to IPV4://166.177.121.0:12273
> relaying data fromIPV4://97.121.170.121:60183 over channelNumber 16387 to IPV4://166.177.121.0:12273
> relaying data fromIPV4://97.121.170.121:60183 over channelNumber 16387 to IPV4://166.177.121.0:12273
> `
> 

Any insight? Here is my configuration 
`
var turn = new Turn({
  // set options
  listeningIps : ['shrek.best'],
  authMech: 'long-term',
  credentials: {
	  user: 'pass',
  },
  defaultAllocatetLifetime : 600000,
  maxAllocateLifetime : 600000,
  debugLevel : 'ALL',
  realm : 'shrek.best',
});`

**Comment by atiertant** [comment]
listeningIps should contain ip not a domain
