### ISSUE TITLE
update js-yaml

### ISSUE THREAD

**Issue by jespertheend** [Atlantis-Software/node-turn#16]
js-yaml currently has two vulnerabilities (1 moderate, 1 high)
https://npmjs.com/advisories/788
https://npmjs.com/advisories/813

The second one doesn't apply to node-turn because node-turn only uses `safeLoad`, but I think the first one might be an issue.

**Comment by atiertant** [comment]
done in 0.0.5

**Comment by jespertheend** [comment]
Thanks!
