### ISSUE TITLE
configuration for server behind NAT - please help

### ISSUE THREAD

**Issue by chintan-golakiya** [Atlantis-Software/node-turn#17]
I am running turn server as nodejs library.

this my current TURN options
```
server = new Turn({
      // set options
      authMech: 'long-term',
      credentials: {
        username: "password"
      },
      debugLevel: "ALL"
      listeningPort: port
    });
```

I am getting this output
_Server is listening on 127.0.0.1:9660
Server is listening on ::1:9660
Server is listening on 172.17.28.34:9660_

I want server to listen to public IP, **what should be my TURN options?**

**Comment by atiertant** [comment]
you should use `externalIps` options and nat all port from your public ip to your server
