### ISSUE TITLE
RangeError [ERR_INVALID_OPT_VALUE]

### ISSUE THREAD

**Issue by Fi1osof** [Atlantis-Software/node-turn#2]
RangeError [ERR_INVALID_OPT_VALUE]: The value "-507861878" is invalid for option "value".

It's make when i set listeningIps 192.168.0.200.

Config:
```
var Turn = require('node-turn');
var server = new Turn({
  // set options
  authMech: 'none',
  listeningIps: ["127.0.0.1", "192.168.0.200"],
});
server.start();

```
Log (added here: https://github.com/Atlantis-Software/node-turn/blob/master/lib/attribute.js#L352 )
```
attribute this.value address { family: 1, address: '192.168.0.200', port: 48551 }
attribute this.msg.magicCookie 554869826
attribute xorAddress  -507861878
buffer.js:1274
    throw new errors.RangeError('ERR_INVALID_OPT_VALUE', 'value', value);
    ^
```

**Comment by Fi1osof** [comment]
Fix for me: set constans.MAGIC_COOKIE in lower value (0x21)

**Comment by atiertant** [comment]
should be fixed in 0.0.2, do you confirm ?

**Comment by atiertant** [comment]
no answer, so close issue...

**Comment by Fi1osof** [comment]
@atiertant sorry for delay... No time to check (this is not my main project). Anyway thanks! I believe that everything works fine now.
