### ISSUE TITLE
does this turn server run on windows?

### ISSUE THREAD

**Issue by webleb** [Atlantis-Software/node-turn#7]
Hi
i was using free turn server and video call was working fine
then i have install this turn server on windows and run the cmd without error and it show node turn start and node start
but no video call can made 
 connection.iceServers.push({
        url: 'turn:publicip:port',
        credential: '',
        username: '' 
i did not set any username or password

**Comment by atiertant** [comment]
yes, it work on windows.
need sample code and logs(turn `debugLevel` to ` 'ALL'`) to help.

**Comment by webleb** [comment]
connection.iceServers.push({
url: 'turn:publicip:port',
credential: '',
username: ''
i did not set any username or password
i get this on Log file
[2019-03-13T20:51:12.368] [FATAL] WIN-52RARMA9562 - { Error: bind EINVAL 2002:3624:a3d7::3624:a3d7:3555
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at _handle.lookup (dgram.js:266:18)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
  code: 'EINVAL',
  errno: 'EINVAL',
  syscall: 'bind',
  address: '2002:3624:a3d7::3624:a3d7',
  port: 3555 }
i think it mean that my server already use the ip address because my port address is not used
and i have try different port but i think i cant try different ip because i think i should use my server ip
which i use to connect to server 
anyway i have stop apache and try again 
same things
but i never try to stop iis because i host my testing files there 
so what you suggest
cmd is clean no error it show turn start node start

**Comment by atiertant** [comment]
see #1
